# Source - https://stackoverflow.com/a/26482170
# Posted by seteropere, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-11, License - CC BY-SA 3.0

##############################################################
#                    Linux Configurations                    #
##############################################################
# The dir. where temporary files will be created.
tempDirForLinux = /tmp
# Where is your dot program located? It will be called externally.
dotForLinux = /usr/bin/dot

##############################################################
#                   Windows Configurations                   #
##############################################################
# The dir. where temporary files will be created.
tempDirForWindows = c:/temp
# Where is your dot program located? It will be called externally.
dotForWindows = "c:/Program Files (x86)/Graphviz 2.28/bin/dot.exe"

##############################################################
#                    Mac Configurations                      #
##############################################################
# The dir. where temporary files will be created.
tempDirForMacOSX = /tmp
# Where is your dot program located? It will be called externally.
dotForMacOSX = /usr/homebrew/bin/dot
